In [8]:
# numpy - basics

In [7]:
import numpy as np

In [9]:
my_list=[1,2,3]

In [10]:
np.array(my_list)

array([1, 2, 3])

In [11]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.random.rand(5)

array([0.13839701, 0.53659814, 0.19143968, 0.00686339, 0.35928833])

In [18]:
np.random.rand(5,5)

array([[0.35860548, 0.16945678, 0.46626528, 0.03529984, 0.59834397],
       [0.03639859, 0.47264541, 0.99243184, 0.46546624, 0.57903425],
       [0.0392363 , 0.14186928, 0.33974879, 0.17559781, 0.8572236 ],
       [0.52658649, 0.5946178 , 0.8123736 , 0.70811937, 0.19857488],
       [0.01039426, 0.77535761, 0.93025559, 0.26124615, 0.38713988]])

In [19]:
np.random.randn(2)

array([-0.18229274,  1.22919911])

In [20]:
np.random.randint(1,100)

96

In [23]:
ranarr=np.random.randint(0, 50, 10) 

In [24]:
ranarr

array([29, 22, 29, 36, 13, 21,  9,  4, 13, 37])

In [25]:
ranarr.reshape(2,5)

array([[29, 22, 29, 36, 13],
       [21,  9,  4, 13, 37]])

In [26]:
ranarr.argmax()

9

In [27]:
ranarr.argmin()

7

In [29]:
ranarr.shape

(10,)

In [32]:
ranarr=ranarr.reshape(5,2)

In [33]:
ranarr

array([[29, 22],
       [29, 36],
       [13, 21],
       [ 9,  4],
       [13, 37]])

In [35]:
ranarr.dtype

dtype('int32')