In [24]:
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  1 02:03:50 2019

@author: sscodes(SANKET SARKAR)
"""


'\nCreated on Sun Sep  1 02:03:50 2019\n\n@author: sscodes(SANKET SARKAR)\n'

In [3]:
import numpy as np

In [7]:
arr=np.arange(0, 11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_of_arr=arr[0:6]

In [10]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:]=99

In [12]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
#By this method the original array also gets changed. So, we use, .copy() method.

In [17]:
arr=np.arange(0, 11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy=arr.copy()

In [20]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr=np.arange(0, 11)

In [26]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [27]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [28]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [30]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [31]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [32]:
arr/arr

C:\Users\SANKET SARKAR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
1/arr

C:\Users\SANKET SARKAR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [33]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [34]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [35]:
np.max(arr)

10

In [36]:
np.min(arr)

0

In [37]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [38]:
np.log(arr)

C:\Users\SANKET SARKAR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])